### ISSUE TITLE
Upwards Offset

### ISSUE THREAD

**Issue by B3rkz** [DiscordStyles/FrostedGlass#41] opened 2022-06-21 06:31 UTC
### Describe the bug
An offset going up making some buttons not visible

### To Reproduce  
Copy and paste a wall of text and it'll offset it

### Screenshots
*If applicable, add screenshots to help explain your problem*
![image](https://user-images.githubusercontent.com/69863524/174731349-2592bf3c-100f-4f56-ba45-fb2029850f3b.png)

### Infomation (please complete the following information)
**Discord channel**: Stable 
**OS**: Windows
**Mod**: BetterDiscord
**Discord language**: English

**Comment by RisenFalcon** [comment] 2022-07-02 06:03
duplicate of #35

**Comment by Gibbu** [comment] 2022-09-26 15:41
Fixed

**Closed by Gibbu** 2022-09-26 15:41 UTC
Labels: bug
