### ISSUE TITLE
extra space below the message bar

### ISSUE THREAD

**Issue by Toshir-96** [DiscordStyles/FrostedGlass#37] opened 2022-05-15 04:41 UTC
### Describe the bug
an extra space pop up below the message bar
![image](https://user-images.githubusercontent.com/99965804/168457551-2af887f6-b507-4088-8294-b37588e74965.png)

### To Reproduce  
i see an extra space below the message bar when i type a long message and the 2nd layer after the bg where it is blur it moves up and i can see only half of the top screen like server name, inbox, etc
![image](https://user-images.githubusercontent.com/99965804/168457534-a47e16d4-010d-4d36-a991-6ee7224467e2.png)

### Screenshots
https://cdn.discordapp.com/attachments/962716737525125130/975254390720036874/unknown.png?size=4096

### Infomation (please complete the following information)
**Discord channel**: Stable  
**OS**: Windows
**Mod**: BetterDiscord
**Discord language**: English  

### Additional context
*Add any other context about the problem here. Remove if not applicable.*

**Comment by RisenFalcon** [comment] 2022-06-06 21:04
duplicate of #35

**Closed** 2022-06-10 14:53 UTC
Labels: bug
